sudo: false
dist: trusty

language: node_js

node_js:
  - "6"

cache:
  directories:
    - $HOME/.cache/yarn

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - google-chrome
    packages:
      - g++-4.8
      - google-chrome-stable
  browserstack:
    username: "alexander1040"
    access_key: "Jauouq9xfuiy9FZq3uA4"
    forcelocal: true

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

before_script:

install:
  - yarn

script:
  - npm run lint:ci
  - npm run test
  - npm run build:ci
  - npm run start
  - npm run bs:local

notifications:
  slack: akveo:q559HckfZMSyZRb803aiLcjH
